import xatra

map = xatra.FlagMap()
map.BaseOption("OpenStreetMap", default=True)
map.BaseOption("Esri.WorldImagery")
map.BaseOption("OpenTopoMap")
map.BaseOption("Esri.WorldPhysical")
map.Data(gadm = "IND.12", value=100)
map.Data(gadm = "IND.12", value=100)
map.Data(gadm = "IND.21", value=300, period=[0, 600])
map.Data(gadm = "IND.22", value=300, period=[0, 600])
map.Data(gadm = "IND.21", value=1000, period=[600, 700])
map.Data(gadm = "IND.22", value=1000, period=[600, 800])
map.TitleBox("Some random data.")
map.slider(speed=1000)
map.show(out_json="tests/map_data.json", out_html="tests/map_data.html")