from .matchers import *

flags = [
    {"name": "DARADA", "matcher": DARADA}, 
    {"name": "MARASA", "matcher": LADAKH}, 
    {"name": "KASHMIR_PROPER", "matcher": KASHMIR_PROPER}, 
    {"name": "DARVA", "matcher": KASHMIR_MISC},
    {"name" : "KASHMIR_TBC", "matcher" : KASHMIR_TBC},
    {"name": "INNER_KAMBOJA", "matcher": INNER_KAMBOJA},
    {"name": "VARNU", "matcher": PSEUDOSATTAGYDIA},
    {"name": "SINDH", "matcher": SINDH},
    {"name": "GANDHARA_W", "matcher": GANDHARA_W},
    {"name": "DOAB_IJ_N", "matcher": DOAB_IJ_N},
    {"name": "DOAB_IJ_S", "matcher": DOAB_IJ_S},
    {"name": "DOAB_JC", "matcher": DOAB_JC},
    {"name": "DOAB_CR", "matcher": DOAB_CR},
    {"name": "DOAB_RS_N", "matcher": DOAB_RS_N},
    {"name": "DOAB_RS_C", "matcher": DOAB_RS_C},
    {"name": "DOAB_RS_S", "matcher": DOAB_RS_S},
    {"name": "TRIGARTA_PROPER", "matcher": TRIGARTA_PROPER},
    {"name": "KUTCH", "matcher": KUTCH},
    {"name": "SURASTRA", "matcher": SURASTRA},
    {"name": "ANARTA", "matcher": ANARTA},
    {"name": "LATA", "matcher": LATA},
    {"name": "KUKURA", "matcher": KUKURA},
    {"name": "MATSYA", "matcher": MATSYA},
    {"name": "BRAHMAVARTA", "matcher": BRAHMAVARTA},
    {"name": "KURU_PROPER", "matcher": KURU_PROPER},
    {"name": "PANCALA_N", "matcher": PANCALA_N},
    {"name": "PANCALA_S", "matcher": PANCALA_S},
    {"name": "SURASENA", "matcher": SURASENA},
    {"name": "VATSA", "matcher": VATSA},
    {"name": "KOSALA", "matcher": KOSALA},
    {"name": "KASI", "matcher": KASI},
    {"name": "MALLA", "matcher": MALLA},
    {"name": "VIDEHA", "matcher": VIDEHA},
    {"name": "SAKYA", "matcher": SAKYA},
    {"name": "LICCHAVI", "matcher": LICCHAVI},
    {"name": "MAGADHA", "matcher": MAGADHA},
    {"name": "AVANTI", "matcher": AVANTI},
    {"name": "AKARA", "matcher": AKARA},
    {"name": "DASARNA", "matcher": DASARNA},
    {"name": "CEDI", "matcher": CEDI},
    {"name": "PULINDA", "matcher": PULINDA},
    {"name": "ANGA", "matcher": ANGA},
    {"name": "GAUDA", "matcher": GAUDA},
    {"name": "RADHA", "matcher": RADHA},
    {"name": "SUHMA", "matcher": SUHMA},
    {"name": "PUNDRA", "matcher" : PUNDRA},
    {"name": "VANGA", "matcher": VANGA},
    {"name": "SAMATATA", "matcher": SAMATATA},
    {"name": "LAUHITYA", "matcher": LAUHITYA},
    {"name": "UTKALA", "matcher": UTKALA},
    {"name": "KALINGA", "matcher": KALINGA},
    {"name": "VIDARBHA", "matcher": VIDARBHA},
    {"name": "RSIKA", "matcher": RSIKA},
    {"name": "MULAKA", "matcher": MULAKA},
    {"name": "ASMAKA", "matcher": ASMAKA},
    {"name": "APARANTA", "matcher": APARANTA},
    {"name": "KUNTALA", "matcher": KUNTALA},
    {"name": "KADAMBA", "matcher": KADAMBA},
    {"name": "GANGA", "matcher": CAUVERIC},
    {"name": "MAHISAKA", "matcher": MAHISAKA},
    {"name": "TELINGA", "matcher": VENGI},
    {"name": "ALUPA", "matcher": TULU},
    {"name": "CERA", "matcher": CERA},
    {"name": "AY", "matcher": AY},
    {"name": "EZHIMALA", "matcher": EZHIMALA},
    {"name": "KANCI", "matcher": KANCI},
    {"name": "COLA", "matcher": COLA},
    {"name": "PANDYA", "matcher": PANDYA},
    {"name": "KONGU", "matcher": KONGU},
    {"name": "SIMHALA", "matcher": SIMHALA},
    {"name": "GEDROSIA", "matcher": BALOCH},
    {"name": "KAMBOJA", "matcher": KAMBOJA},
    {"name": "MERU", "matcher": MERU},
    {"name": "ZARANJ", "matcher": ZARANJ},
    {"name": "KANDAHAR", "matcher": KANDAHAR},
    {"name": "HERAT", "matcher": HERAT},
    {"name": "MARGIANA", "matcher": MARGIANA},
    {"name": "BACTRIA", "matcher": BACTRIA},
    {"name": "SOGDIA_PROPER", "matcher": SOGDIA_PROPER},
    {"name": "FERGHANA", "matcher": FERGHANA},
    {"name": "KHWAREZM", "matcher": KHWAREZM},
    {"name": "KASHGAR", "matcher": KASHGAR},
    {"name": "KHOTAN", "matcher": KHOTAN},
    {"name": "AGNI", "matcher": AGNI},
    {"name": "AKSU", "matcher": AKSU},
    {"name": "KUCHA", "matcher": KUCHA},
    {"name": "ROURAN", "matcher": ROURAN},
    {"name": "QIEMO", "matcher": QIEMO},
    {"name": "KORLA", "matcher": KORLA},
    {"name": "TURFAN", "matcher": TURFAN},
    {"name" : "COORG", "matcher" : COORG},
    {"name" : "YYY_GREAT_FOREST", "matcher" : YYY_GREAT_FOREST},
    {"name" : "YYY_KALAKAVANA", "matcher" : YYY_KALAKAVANA},
    {"name" : "YYY_MARU", "matcher" : YYY_MARU},
    {"name" : "YYY_NAIMISA", "matcher" : YYY_NAIMISA},
    {"name" : "YYY_HIMALAYAN", "matcher" : YYY_HIMALAYAN},
    {"name" : "ZZZ_BAYALU", "matcher" : ZZZ_BAYALU},
    {"name" : "ZZZ_GREATER_PUNE", "matcher" : ZZZ_GREATER_PUNE},
    {"name" : "ZZZ_HADOTI", "matcher" : ZZZ_HADOTI},
    {"name" : "ZZZ_BIHAR_NORTHEAST", "matcher" : ZZZ_BIHAR_NORTHEAST},
    {"name" : "ZZZ_BAHAWALPUR", "matcher" : ZZZ_BAHAWALPUR}
]

custom_colors = {
    flag["name"] : '#444444' # grey these out
    for flag in flags 
    if flag["name"].startswith("YYY_")
    or flag["name"].startswith("ZZZ_")}